"""empty message

Revision ID: 7793d3b9fc6d
Revises: 
Create Date: 2022-10-05 23:03:42.313613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7793d3b9fc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('rest_pswd', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'rest_pswd')
    # ### end Alembic commands ###
