"""empty message

Revision ID: 786c63726eea
Revises: 7793d3b9fc6d
Create Date: 2022-10-06 17:13:32.906451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786c63726eea'
down_revision = '7793d3b9fc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('request_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'request_date')
    # ### end Alembic commands ###
