"""empty message

Revision ID: 830e8f4cff8b
Revises: 
Create Date: 2023-01-08 12:13:39.931320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830e8f4cff8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('account_bank', sa.Integer(), nullable=True))
    op.add_column('restaurant', sa.Column('account_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'banks', ['account_bank'], ['bank_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'account_name')
    op.drop_column('restaurant', 'account_bank')
    # ### end Alembic commands ###
